# Generated by Django 5.0.4 on 2024-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0005_timeslot_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
