# Generated by Django 5.0.3 on 2024-04-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0006_alter_timeslot_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='SGs1s2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
    ]
