# Generated by Django 5.0.3 on 2024-04-20 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0008_sgs99s100'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SGs99s100',
            new_name='SG0001s101s102',
        ),
    ]
