# Generated by Django 5.0.3 on 2024-04-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0010_dynamictable'),
    ]

    operations = [
        migrations.CreateModel(
            name='barcode_app_s3s4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.CharField(max_length=100)),
                ('present', models.BooleanField(default=False)),
            ],
        ),
    ]
