# Generated by Django 5.0.3 on 2024-04-22 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0012_rename_barcode_app_s3s4_barcode_app_sg0001s3s4'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='barcode_app_sg0001s3s4',
            new_name='barcdeo_app_s3s4',
        ),
    ]
