# Generated by Django 5.0.3 on 2024-04-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0016_s13s14'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='s13s14',
            new_name='Rb0001s13s14',
        ),
    ]
